### ISSUE TITLE
[먼슬리] 레이아웃 제작

### ISSUE THREAD

**Issue by flowersayo** [EFUB-LakkuLakku/LakkuLakku-Front#9]
- [x] Monthly 레이아웃 제작
- [x]  Wrapper  컴포넌트 생성
- [x] Background 컴포넌트 생성 

**Monthly.js**
```
<Box>
      <DateBar />
      {/*<Calendar/> 달력 */}
      MonthlyPage
    </Box>
```

개별 컴포넌트 개발할때 레이아웃을 미리 만들어두는게 크기 조정하는게 편하실 것 같아서 미리 작업했어용!
PR 날리고 합치는거보다는 그냥 바로 레이아웃 위에 작업하시는 게 편할 것 같아서 main에 바로 푸시했습니답  

@Kyoungminn 캘린더 컴포넌트 개발 후에 해당부분 주석 해제만 해주시면 될 것 같아옹!
아마 캘린더 최상위 div에  `flex : 1` 주시면 DateBar 제외한 나머지 부분을 꽉채워줄 것 같습니다 🤗🤗

![image](https://user-images.githubusercontent.com/86418674/178161088-56f03ed0-a0ff-4c9e-b952-0019b4599f00.png)
![image](https://user-images.githubusercontent.com/86418674/178161291-114021f9-3cb0-47fe-9fab-4a9ba344a6de.png)

# 전체 레이아웃 코드 동작 원리

- px 대신 rem 사용 -> rem은 html 엘리먼트의 font-size에 비례하는 상대적 단위
- 피그마 와이어프레임을 0.7배 축소시켜서 사용할 수 있도록 다음과 같이 index.css의 font-size 수정

**index.css** 
```
html {
  font-size: calc(6.25% * `0.7`); /*1rem = 0.7px 이 되도록 맞춤*/
}
```

- 1rem 은 본래 16px을 의미.
- 따라서 6.25% = 1px 
- 1px * 0.7 = 0.7px 
- 이제 html 하위 element에서 1rem은 0.7px을 의미하게 된다!
- 따라서 rem으로는 피그마 수치대로 부여해도 더이상 화면 크기가 초과되지 않음
- ex. 내부 화면이 1380 x 905 이므로 다음과 같은 css 코드를 부여하면 실제로는 가로 : 1380 x 0.7px , 세로 : 905 x 0.7px 의 크기만큼 차지하게 된다.
```
  width: 1380rem;
  height: 905rem;
  margin: 60rem 30rem;
```

![image](https://user-images.githubusercontent.com/86418674/178187108-378b0ea0-0447-4394-add6-14d234fd5ead.png)

 아무래도 피그마 디자인은 1440 해상도 모니터 기준이라 제 노트북은 화면이 작아서  디자인(1380 x 905 )대로 그대로 px 적용하면 한 화면에 다 안보이고 스크롤이 생겨버리더라구요 😢
조금 축소시키더라도 한화면에 모두 보이는게 좋을 것 같아서
그래서 저는 크기는 그대로 못가져갈 수 있지만 비율은 그대로 유지하면서, 가능한 한 화면 크기를 크게하는 방법이 좋을 것 같다고 생각했습니다. 
우선 레이아웃을 짤 때 rem단위를 사용하여서 html 루트의 font-size 만 조정하면 
화면의 배율은 자유롭게 설정할 수 있는 것 같습니다..!!
그러나 한가지 걸리는것이 rem은 보통 폰트사이즈 조정할 때 쓰는 단위라고 알고있었는데 요런식으로 레이아웃 짤때도 활용해도 괜찮은걸까용?! 처음에는 `document.documentElement.scrollWidth` 로 웹페이지 크기를 받아와서 이에 적합한 최적의 크기로 보여주는 방식도 생각해보았는데 그럼 코드가 너무 복잡해질 것 같아서 우선은 보류했습니다😅  

지금 방법도 뭔가 썩 좋은 방법은 아닌 것 같아 다른 좋은 방법이 있다면 의견 남겨주시면 감사하겠습니다! 
흑흑 css 공부를 더 했어야했는데 아직 많이 부족한 것 같네용.....
혹시 페이지 구현하신 다른 분들은 화면 크기를 어떤식으로 처리하셨나요? 

📌참고한 링크 : 
https://blog.jeongtae.com/rem-%EA%B3%A0%EC%B0%B0

**Comment by rajoo1120** [comment]
우선 저는 뷰포인트랑 %를 이용해서 화면에 꽉차게 보이는 걸 목표로 했어요! 
배경은 100vw, 100vh를 적용하고, 하위에 있는 박스는 그 뷰포인트를 기준으로 80%, 70%를 채우는 식으로 했습니다.
근데 안그래도 이것도 화면 크기에 따라 스크롤이 생기는 것 같아 이번주 회의 때 말씀드리려 했었습니다 .. ㅠ.ㅠ
저는 잘 모르지만 rem 단위도 좋은 것 같은데 회의 때까지 더 좋은 방법이 있을지 찾아볼게요

**Comment by paya17** [comment]
저도 피그마 디자인이랑 제 화면 크기랑 차이가 나서 말씀 드리려 했었는데 이슈 올려주셔서 감사해요..! 
전에 해린님께서 rem단위를 사용하는 게 좋다고 듣긴 했었어요...!
저도 다른 좋은 방법 있는지 더 찾아보겠습니다!

**Comment by Kyoungminn** [comment]
저도 rem 단위를 사용하는게 좋을 것 같은데 혹시 다른 방법이 있는지 찾아볼게요!
